---
kind: pipeline
name: "Push"

concurrency:
  limit: 2

---
kind: pipeline
name: "New version"

concurrency:
  limit: 2

steps:
  - name: "Build Docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
      tags: ${DRONE_COMMIT:0:7}

  - name: "Update image tag at odc-deployments"
    image: quay.io/openware/goci:0.0.6
    environment:
      GIT_TOKEN:
        from_secret: kite_bot_key
      GIT_URL:
        from_secret: odc_repo_url
    commands:
      - export tag=$${DRONE_COMMIT:0:7}
      - /app/goci -component=frontend -path=nairaex-uat-ci-disabled/versions.yml -tag=$tag versions
    depends_on:
      - "Build Docker image"

trigger:
  branch:
    - master
    - "2-*-stable"
    - "integration/*"
    - "hotfix/*"
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
