secrets:
  global:
    scopes:
      public:
        api:
          authUrl: 'http://localhost:9002/api/v2/barong'
          tradeUrl: 'http://localhost:9002/api/v2/peatio'
          finexUrl: 'http://localhost:9002/api/v2/finex'
          applogicUrl: 'http://localhost:9002/api/v2/applogic'
          rangerUrl: 'wss://localhost:9002/api/v2/ranger'
        minutesUntilAutoLogout: '35'
        withCredentials: 'false'
        finex: 'false'
        gaTrackerKey: ''
        rangerReconnectPeriod: '1'
        msAlertDisplayTime: '5000'
        incrementalOrderBook: 'true'
        isResizable: 'false'
        isDraggable: 'false'
        languages: ['en', 'ru']
        sessionCheckInterval: '15000'
        balancesFetchInterval: '3000'
        captcha_type: none
        password_min_enthropy: '14'
        passwordEntropyStep: '14'
        showLanding: 'true'
        sentryEnabled: 'false'
        kycSteps: [
          'email',
          'phone',
          'profile',
          'document',
          'address',
        ]
        msPricesUpdates: 3000
      private:
        key1: value
      secret:
        key1: value

  sonic:
    scopes:
      public:
        key1: value
      private:
        database_driver: "mysql"
        database_host: localhost
        database_port: "3306"
        database_user: root
        database_name: opendax_development
        hostname: http://localhost:9002
        barong_url: http://localhost:9002/api/v2/barong
        applogic_url: http://localhost:9002/api/v2/applogic
        peatio_url: http://localhost:9002/api/v2/peatio
        vault_addr: http://localhost:8200
        deployment_id: nairaex
      secret:
        vault_token: changeme

  finex:
    scopes:
      public:
        key1: value
      private:
        maxAmonut: '5000'
        minAmount: '1'
        currency: 'usdt'
      secret:
        vault_token: changeme

  forex:
    scopes:
      public:
        key1: value
      private:
        config: '{"sources":[{"pair":"daieth","provider":"bitfinex","base":"dai","quote":"eth","base_contract":"0x6B175474E89094C44Da98b954EedeAC495271d0F","period":6000},{"pair":"rlyeth","provider":"bitfinex","base":"rly","quote":"eth","base_contract":"0xf1f955016EcbCd7321c7266BccFB96c68ea5E49b","base_decimal":18,"period":120},{"pair":"eurusd","provider":"bitfinex","base":"eur","quote":"usd","period":600}]}'
      secret:
        key1: value
